name = "aci"
main = "src/index.js"
compatibility_date = "2025-10-12"
workers_dev = false

[[routes]] 
pattern = "aci.aliasmail.cc"
custom_domain = true

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[ai]
binding = "AI"

[[r2_buckets]] 
binding = "r2-aci" 
bucket_name = "aci" 