name = "aci"
main = "src/index.js"
compatibility_date = "2025-10-12"
workers_dev = false

[[routes]] 
pattern = "aci.aliasmail.cc"
custom_domain = true

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[ai]
binding = "WORKERS_AI"

[[r2_buckets]]
binding = "R2"
bucket name = "aci" 

[[vectorize]]
binding = "AUTORAG"
index_name = "autorag"

[durable_objects]
bindings = [
  { name = "MCP", class_name = "MyMCP" }
]

[browser]
binding = "RENDER"
